from modules.static.config_keys import *

tasks_config = {
    ConfigSections.SIMULATOR: {SimulatorKeys.DEVICE_ADDRESS: "127.0.0.1:16416"},
    ConfigSections.EXPLOIT: {"state": False, "nexttime": "2019/06/01 00:00:00"},
    ConfigSections.ENEMY: {
        EnemyKeys.STATE: False,
        EnemyKeys.NEXTTIME: "2019/06/01 00:00:00",
        EnemyKeys.ENDTIME: "2019/06/01 00:00:00",
        EnemyKeys.LOOPTIME: 60,
    },
    ConfigSections.MYFIGHT: {
        MyFightKeys.STATE: False,
        MyFightKeys.NEXTTIME: "2019/06/01 00:00:00",
        MyFightKeys.ENDTIME: "2019/06/01 00:00:00",
        MyFightKeys.LOOPTIME: 0,
    },
    ConfigSections.RANKING: {RankingKeys.STATE: False, RankingKeys.NEXTTIME: "2019/06/01 00:00:00"},
    ConfigSections.BATTLEDESTORY: {
        BattleDestoryKeys.STATE: False,
        BattleDestoryKeys.NEXTTIME: "2019/06/01 00:00:00",
        BattleDestoryKeys.ENDTIME: "2019/06/01 00:00:00",
        BattleDestoryKeys.LOOPTIME: 60,
    },
    ConfigSections.PRACTICE_LAND: {
        PracticeLandKeys.STATE: False,
        PracticeLandKeys.NEXTTIME: "2019/06/01 00:00:00",
        PracticeLandKeys.X: 123,
        PracticeLandKeys.Y: 123,
        PracticeLandKeys.STAGE: 0,
        PracticeLandKeys.ADDRESS: '',
        PracticeLandKeys.DRAFT: True,
        PracticeLandKeys.NUM: 1,
        PracticeLandKeys.ACTION_LIST: 1,
        PracticeLandKeys.MAX_DISTANCE: 300,
        PracticeLandKeys.TIME_CONSUMING: 0,
        PracticeLandKeys.MY_REMAINING: 30000,
        PracticeLandKeys.ENEMY_REMAINING: 30000
    },
    ConfigSections.PRACTICE_LAND_1: {
        PracticeLandKeys.STATE: False,
        PracticeLandKeys.NEXTTIME: "2019/06/01 00:00:00",
        PracticeLandKeys.X: 123,
        PracticeLandKeys.Y: 123,
        PracticeLandKeys.STAGE: 0,
        PracticeLandKeys.ADDRESS: '',
        PracticeLandKeys.DRAFT: True,
        PracticeLandKeys.NUM: 1,
        PracticeLandKeys.ACTION_LIST: 1,
        PracticeLandKeys.MAX_DISTANCE: 300,
        PracticeLandKeys.TIME_CONSUMING: 0,
        PracticeLandKeys.MY_REMAINING: 30000,
        PracticeLandKeys.ENEMY_REMAINING: 30000
    },
    ConfigSections.PRACTICE_LAND_2: {
        PracticeLandKeys.STATE: False,
        PracticeLandKeys.NEXTTIME: "2019/06/01 00:00:00",
        PracticeLandKeys.X: 123,
        PracticeLandKeys.Y: 123,
        PracticeLandKeys.STAGE: 0,
        PracticeLandKeys.ADDRESS: '',
        PracticeLandKeys.DRAFT: True,
        PracticeLandKeys.NUM: 1,
        PracticeLandKeys.ACTION_LIST: 1,
        PracticeLandKeys.MAX_DISTANCE: 300,
        PracticeLandKeys.TIME_CONSUMING: 0,
        PracticeLandKeys.MY_REMAINING: 30000,
        PracticeLandKeys.ENEMY_REMAINING: 30000
    },
    ConfigSections.PRACTICE_LAND_3: {
        PracticeLandKeys.STATE: False,
        PracticeLandKeys.NEXTTIME: "2019/06/01 00:00:00",
        PracticeLandKeys.X: 123,
        PracticeLandKeys.Y: 123,
        PracticeLandKeys.STAGE: 0,
        PracticeLandKeys.ADDRESS: '',
        PracticeLandKeys.DRAFT: True,
        PracticeLandKeys.NUM: 1,
        PracticeLandKeys.ACTION_LIST: 1,
        PracticeLandKeys.MAX_DISTANCE: 300,
        PracticeLandKeys.TIME_CONSUMING: 0,
        PracticeLandKeys.MY_REMAINING: 30000,
        PracticeLandKeys.ENEMY_REMAINING: 30000
    },
    ConfigSections.PRACTICE_LAND_4: {
        PracticeLandKeys.STATE: False,
        PracticeLandKeys.NEXTTIME: "2019/06/01 00:00:00",
        PracticeLandKeys.X: 123,
        PracticeLandKeys.Y: 123,
        PracticeLandKeys.STAGE: 0,
        PracticeLandKeys.ADDRESS: '',
        PracticeLandKeys.DRAFT: True,
        PracticeLandKeys.NUM: 1,
        PracticeLandKeys.ACTION_LIST: 1,
        PracticeLandKeys.MAX_DISTANCE: 300,
        PracticeLandKeys.TIME_CONSUMING: 0,
        PracticeLandKeys.MY_REMAINING: 30000,
        PracticeLandKeys.ENEMY_REMAINING: 30000
    },
    ConfigSections.ATTACK_LAND: {
        ATTACK_LAND.STATE: False,
        ATTACK_LAND.NEXTTIME: "2019/06/01 00:00:00",
        ATTACK_LAND.X: 123,
        ATTACK_LAND.Y: 123,
        ATTACK_LAND.STAGE: 0,
        ATTACK_LAND.ADDRESS: '',
        ATTACK_LAND.DRAFT: True,
        ATTACK_LAND.NUM: 1,
        ATTACK_LAND.ACTION_LIST: 1,
        ATTACK_LAND.MAX_DISTANCE: 300,
        ATTACK_LAND.TIME_CONSUMING: 0,
        ATTACK_LAND.MY_REMAINING: 30000,
        ATTACK_LAND.ENEMY_REMAINING: 30000
    },
    ConfigSections.ATTACK_LAND_1: {
        ATTACK_LAND.STATE: False,
        ATTACK_LAND.NEXTTIME: "2019/06/01 00:00:00",
        ATTACK_LAND.X: 123,
        ATTACK_LAND.Y: 123,
        ATTACK_LAND.STAGE: 0,
        ATTACK_LAND.ADDRESS: '',
        ATTACK_LAND.DRAFT: True,
        ATTACK_LAND.NUM: 1,
        ATTACK_LAND.ACTION_LIST: 1,
        ATTACK_LAND.MAX_DISTANCE: 300,
        ATTACK_LAND.TIME_CONSUMING: 0,
        ATTACK_LAND.MY_REMAINING: 30000,
        ATTACK_LAND.ENEMY_REMAINING: 30000
    },
    ConfigSections.ATTACK_LAND_2: {
        ATTACK_LAND.STATE: False,
        ATTACK_LAND.NEXTTIME: "2019/06/01 00:00:00",
        ATTACK_LAND.X: 123,
        ATTACK_LAND.Y: 123,
        ATTACK_LAND.STAGE: 0,
        ATTACK_LAND.ADDRESS: '',
        ATTACK_LAND.DRAFT: True,
        ATTACK_LAND.NUM: 1,
        ATTACK_LAND.ACTION_LIST: 1,
        ATTACK_LAND.MAX_DISTANCE: 300,
        ATTACK_LAND.TIME_CONSUMING: 0,
        ATTACK_LAND.MY_REMAINING: 30000,
        ATTACK_LAND.ENEMY_REMAINING: 30000
    },
    ConfigSections.ATTACK_LAND_3: {
        ATTACK_LAND.STATE: False,
        ATTACK_LAND.NEXTTIME: "2019/06/01 00:00:00",
        ATTACK_LAND.X: 123,
        ATTACK_LAND.Y: 123,
        ATTACK_LAND.STAGE: 0,
        ATTACK_LAND.ADDRESS: '',
        ATTACK_LAND.DRAFT: True,
        ATTACK_LAND.NUM: 1,
        ATTACK_LAND.ACTION_LIST: 1,
        ATTACK_LAND.MAX_DISTANCE: 300,
        ATTACK_LAND.TIME_CONSUMING: 0,
        ATTACK_LAND.MY_REMAINING: 30000,
        ATTACK_LAND.ENEMY_REMAINING: 30000
    },
    ConfigSections.ATTACK_LAND_4: {
        ATTACK_LAND.STATE: False,
        ATTACK_LAND.NEXTTIME: "2019/06/01 00:00:00",
        ATTACK_LAND.X: 123,
        ATTACK_LAND.Y: 123,
        ATTACK_LAND.STAGE: 0,
        ATTACK_LAND.ADDRESS: '',
        ATTACK_LAND.DRAFT: True,
        ATTACK_LAND.NUM: 1,
        ATTACK_LAND.ACTION_LIST: 1,
        ATTACK_LAND.MAX_DISTANCE: 300,
        ATTACK_LAND.TIME_CONSUMING: 0,
        ATTACK_LAND.MY_REMAINING: 30000,
        ATTACK_LAND.ENEMY_REMAINING: 30000
    },

    ConfigSections.SPARTA_ATTACK_LAND: {
        SPARTA_ATTACK_LAND.STATE: False,
        SPARTA_ATTACK_LAND.NEXTTIME: "2019/06/01 00:00:00",
        SPARTA_ATTACK_LAND.X: 123,
        SPARTA_ATTACK_LAND.Y: 123,
        SPARTA_ATTACK_LAND.STAGE: 0,
        SPARTA_ATTACK_LAND.ADDRESS: '',
        SPARTA_ATTACK_LAND.MAX_DISTANCE: 300,
        SPARTA_ATTACK_LAND.TIME_CONSUMING: 0
    },
    ConfigSections.FIGHT_CITY: {
        FightCityKeys.STATE: False,
        FightCityKeys.NEXTTIME: "2019/06/01 00:00:00",
        FightCityKeys.X: 123,
        FightCityKeys.Y: 123,
        FightCityKeys.MODE: 1,
        FightCityKeys.STAGE: 0,
        FightCityKeys.ADDRESS: '',
        FightCityKeys.TIME_CONSUMING: 0
    },
    ConfigSections.MartialArts: {
        MartialArtsKeys.STATE: False,
        MartialArtsKeys.NEXTTIME: "2019/06/01 00:00:00",
        MartialArtsKeys.DIFFICULTY: 5,
        MartialArtsKeys.RETRY: 20
    }
}
